# Generated by Django 6.0 on 2025-12-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep_rise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fitness_goal',
        ),
    ]
