# Generated by Django 6.0 on 2025-12-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_rise', '0002_remove_profile_activity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='muscle_groups',
        ),
        migrations.AlterField(
            model_name='stepgoalplan',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
