# Generated by Django 6.0 on 2026-01-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_rise', '0003_remove_workout_muscle_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
