# Generated by Django 6.0 on 2026-01-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_rise', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='steplog',
            name='calories_burned',
            field=models.FloatField(default=0, help_text='Energy expenditure in kcal'),
        ),
        migrations.AddField(
            model_name='steplog',
            name='distance_meters',
            field=models.FloatField(default=0, help_text='Distance travelled in meters'),
        ),
        migrations.AddField(
            model_name='steplog',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Time spent active in minutes'),
        ),
    ]
