# Generated by Django 6.0 on 2026-01-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep_rise', '0006_steplog_calories_burned_steplog_distance_meters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepgoalplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='StepGoalOverride',
        ),
        migrations.DeleteModel(
            name='StepGoalPlan',
        ),
    ]
