# Generated by Django 6.0 on 2026-01-28 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_rise', '0008_profile_is_email_verified_profile_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance')], default='muscle_gain', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitness_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkoutRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='The generated workout plan')),
                ('saved_weight', models.FloatField(blank=True, null=True)),
                ('saved_goal', models.CharField(blank=True, max_length=20, null=True)),
                ('saved_level', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='rep_rise.profile')),
            ],
        ),
    ]
