# Generated by Django 6.0 on 2026-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_rise', '0009_profile_fitness_goal_profile_fitness_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='Target/Ideal Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('maintenance', 'Maintenance')], default='muscle_gain', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Current Weight in kg', null=True),
        ),
    ]
