# Generated by Django 6.0 on 2026-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_rise', '0010_profile_target_weight_alter_profile_fitness_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('maintenance', 'Maintenance')], max_length=20, null=True),
        ),
    ]
